ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine AS base
WORKDIR /usr/app

FROM base AS build
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci
COPY . .
RUN npm run build

FROM nginx:alpine AS production
COPY --from=build /usr/app/dist/frontend/browser /usr/share/nginx/html
COPY ./config/default.conf /etc/nginx/conf.d/default.conf
COPY ./public/env.js /usr/share/nginx/html/env2.js
CMD ["sh", "-c", "envsubst < /usr/share/nginx/html/env2.js > /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"]
