apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parameters
  namespace: ns-dev
data:
  apiUrl: http://dev-api.mycompany.com
  domain: http://dev.mycompany.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-server-web
  labels:
    app: frontend
    env: dev
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
      namespace: ns-dev
    spec:
      containers:
        - name: container01
          image: python:3.7-alpine
          command: [
            "sh",
            "-c",
            "echo 'página desde python' > index.html && python -m http.server 8080"
          ]
          env:
            - name: TITLE
              value: "Frontend App"
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: parameters
                  key: apiUrl
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: parameters
                  key: domain